apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c -f docker-compose.yml
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: ghostfolio
  name: ghostfolio
spec:
  type: LoadBalancer
  ports:
    - name: ghostfolio-svc
      port: 3333
      targetPort: 3333
  selector:
    io.kompose.service: ghostfolio
